# Generated by Django 2.2.10 on 2020-04-30 23:01

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pv',
            fields=[
                ('IA_System_Code', models.AutoField(primary_key=True, serialize=False)),
                ('IA_code', models.CharField(max_length=150)),
                ('Date_recieved', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('Pv_reference', models.CharField(max_length=120, unique=True)),
                ('Source_of_Funding', models.CharField(choices=[('GOG', 'GOG'), ('Others', 'Others')], max_length=50)),
                ('Cost_center', models.CharField(choices=[('Cost Center 1', 'Cost Center 1'), ('Cost Center 2', 'Cost Center 2'), ('Cost Center 3', 'Cost Center 3'), ('Cost Center 4', 'Cost Center 4'), ('Cost Center 5', 'Cost Center 5')], max_length=50)),
                ('Payee', models.CharField(blank=True, max_length=500, null=True)),
                ('Description', models.CharField(max_length=500)),
                ('Account_code', models.CharField(max_length=350)),
                ('Gross_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Withholding_tax', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Net_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Status', models.CharField(choices=[('Completed', 'Completed'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], max_length=60)),
                ('Remarks', models.CharField(blank=True, max_length=500)),
                ('Acc_Impress', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=350)),
                ('Date_returned', models.DateField(blank=True, null=True)),
                ('Type_of_accounts', models.CharField(choices=[('Sub CF', 'Sub CF'), ('Special', 'Special'), ('Directors', 'Directors'), ('Operations', 'Operations'), ('LSGDP', 'LSGDP'), ('DWAP', 'DWAP'), ('Capacity(USD)', 'Capacity(USD)')], max_length=100)),
                ('Type_of_pv', models.CharField(choices=[('General', 'General'), ('Honorarium', 'Honorarium')], max_length=20)),
                ('returned_to_chest', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('created', models.DateTimeField(null=True)),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pv.Profile')),
            ],
            options={
                'ordering': ['-IA_System_Code'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=300)),
                ('rank', models.CharField(choices=[('A.A.G', 'A.A.G'), ('AG', 'AG'), ('ARTISAN GD I', 'ARTISAN GD I'), ('ARTISAN GD II', 'ARTISAN GD II'), ('ARTISAN GD III', 'ARTISAN GD III'), ('ARTISAN GRADE', 'ARTISAN GRADE'), ('ASST SECURITY GUARD', 'ASST SECURITY GUARD'), ('ASST. CHIEF SEC.OFF.', 'ASST. CHIEF SEC.OFF.'), ('ASST. DIR', 'ASST. DIR'), ('AUD EXAMINER', 'AUD EXAMINER'), ('AUDIT ASST', 'AUDIT ASST'), ('AUDITOR', 'AUDITOR'), ('CHEIF SEC. OFF', 'CHEIF SEC. OFF'), ('CLEANER', 'CLEANER'), ('CLEANER GD I', 'CLEANER GD I'), ('CLEANER GD II', 'CLEANER GD II'), ('DAG', 'DAG'), ('DIRECTOR', 'DIRECTOR'), ('DIR GD. I', 'DIR GD. I'), ('DIR GD. II', 'DIR GD. II'), ('DIR GD. III', 'DIR GD. III'), ('EX OF A/C', 'EX OF A/C'), ('HEAD LAB', 'HEAD LAB'), ('HEAD WATCHMAN', 'HEAD WATCHMAN'), ('LAB GD II', 'LAB GD II'), ('LAB GD I', 'LAB GD I'), ('LAB./CLEARN', 'LAB./CLEARN'), ('P.E.A', 'P.E.A'), ('PRIN.AUD', 'PRIN.AUD'), ('PRIN.RECEPTIONIST', 'PRIN.RECEPTIONIST'), ('PRIN. SEC OFF', 'PRIN. SEC OFF'), ('PRIN .STORE OFF', 'PRIN .STORE OFF'), ('PRIN. TYPIST', 'PRIN. TYPIST'), ('RECEPTIONIST', 'RECEPTIONIST'), ('PRIVATE SEC', 'PRIVATE SEC'), ('RECEPTIONIST', 'RECEPTIONIST'), ('S.E.A', 'S.E.A'), ('SEC OFF.', 'SEC OFF.'), ('SEN EST.ASSIST', 'SEN EST.ASSIST'), ('SEN STENO.', 'SEN STENO.'), ('SNR. TYPIST', 'SNR. TYPIST'), ('SNR. AUDITOR', 'SNR. AUDITOR'), ('SRN. PRIV. SEC', 'SRN. PRIV. SEC'), ('SNR. SEC OFF', 'SNR. SEC OFF'), ('SNR. TELEPHONIST', 'SNR. TELEPHONIST'), ('SNR. TRANS. OFFICER', 'SNR. TRANS. OFFICER'), ('STENO', 'STENO'), ('STENO. SEC', 'STENO. SEC'), ('STORES ASSISTANT', 'STORES ASSISTANT'), ('SWEEPER', 'SWEEPER'), ('TELEPHONIST', 'TELEPHONIST'), ('TRANSPORT OFF', 'TRANSPORT OFF'), ('TYPIST', 'TYPIST'), ('TYPIST GD I', 'TYPIST GD I'), ('WATCHMAN', 'WATCHMAN'), ('YARD FOR', 'YARD FOR')], max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('Pv_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pvreference', to='pv.Pv')),
            ],
        ),
    ]
