# Generated by Django 2.2.10 on 2020-05-01 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0005_auto_20200501_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pv',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pv',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='pv',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
