# Generated by Django 2.2.10 on 2020-05-01 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pv', '0006_auto_20200501_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pv',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
