# Generated by Django 2.2.10 on 2020-05-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0007_auto_20200501_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pv',
            old_name='created',
            new_name='createds',
        ),
        migrations.RenameField(
            model_name='pv',
            old_name='modified',
            new_name='modifieds',
        ),
    ]
