# Generated by Django 2.2.10 on 2020-05-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0008_auto_20200502_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_id',
        ),
    ]
