# Generated by Django 2.2.10 on 2020-05-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0009_remove_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='rank',
            field=models.CharField(max_length=300),
        ),
    ]
