# Generated by Django 2.2.10 on 2020-05-06 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0010_auto_20200506_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='Date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pv.Grade'),
        ),
    ]
