# Generated by Django 3.0.6 on 2020-05-10 16:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0011_auto_20200506_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='staff',
            name='rank',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pv.Grade'),
        ),
    ]
