# Generated by Django 3.0.7 on 2020-07-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0013_auto_20200707_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
    ]
